name: AUTO_MERGE
on:
  pull_request:
    # types: [labeled]

jobs:
  auto-merge:
    # if: github.event.label.name == 'Ready to merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: git log
      - run: git checkout HEAD
      - run: git log
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: git rebase --onto origin/master
