name: AUTO_MERGE
on:
  pull_request:
    # types: [labeled]

jobs:
  auto-merge:
    # if: github.event.label.name == 'Ready to merge'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: git clone ${{ github.repositoryUrl }} ./
      - run: ls -lrta
      - run: git fetch origin
      - run: git branch
      - run: git checkout origin/${{ github.event.pull_request.head.ref }}
      - run: git log
