name: AUTO_MERGE
on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "It works"
          echo "It works 2"
          echo "It works 3"
