name: AUTO_MERGE
on:
  pull_request:
    # types: [labeled]

jobs:
  auto-merge:
    # if: github.event.label.name == 'Ready to merge'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: git log
      - run: git reset ${{ github.event.pull_request.head.sha }} --hard
      - run: git log
      - run: git rebase origin/master
