name: AUTO_MERGE
on:
  pull_request:
    # types: [labeled]

jobs:
  auto-merge:
    # if: github.event.label.name == 'Ready to merge'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: git clone https://x-access-token:${{ GITHUB_TOKEN }}@github.com/${{ github.repository }} ./
      - run: git checkout ${{ github.event.pull_request.head.ref }}
      - run: git rebase ${{ github.event.pull_request.base.ref }}
      - run: git push --force-with-lease

