name: AUTO_MERGE
on:
  pull_request:
    # types: [labeled]

jobs:
  auto-merge:
    # if: github.event.label.name == 'Ready to merge'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: git log
      - run: git checkout HEAD~1
      - run: git log
      - run: git rebase --onto origin/master
