name: AUTO_MERGE
on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "GITHUB_EVENT_PATH=" $GITHUB_EVENT_PATH
